version: "3"

name: mink-dev

volumes:
  db_data:
  s3_data:

services:
  pg_database:
    container_name: 'mink-dev-postgres'
    image: postgres:latest
    volumes:
      - ~/Desktop/mink-postgre/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'mink'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'mink'
    ports:
      - "5432:5432"
  
  s3:
    container_name: 'mink-dev-minio_s3'
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3_data:/data
    environment:
      MINIO_ROOT_USER: 'mink'
      MINIO_ROOT_PASSWORD: 'password'
    command: server /data --console-address ":9001"